services:
  # Backend Laravel con Sail
  laravel.test:
    build:
      context: ./backend
      dockerfile: Dockerfile
      args:
        WWWGROUP: "${WWWGROUP:-1000}"
    image: sail-8.4/app
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "${APP_PORT:-80}:80"
      - "${VITE_PORT:-5173}:${VITE_PORT:-5173}"
    environment:
      WWWUSER: "${WWWUSER:-1000}"
      LARAVEL_SAIL: 1
      XDEBUG_MODE: "${SAIL_XDEBUG_MODE:-off}"
      XDEBUG_CONFIG: "${SAIL_XDEBUG_CONFIG:-client_host=host.docker.internal}"
      IGNITION_LOCAL_SITES_PATH: "${PWD}/backend"
    volumes:
      - ./backend:/var/www/html
      - /var/www/html/vendor
    networks:
      - sail
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy

  # Frontend Nuxt.js
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: gestor-frontend
    ports:
      - "${FRONTEND_PORT:-3000}:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      NODE_ENV: development
      HOST: 0.0.0.0
      PORT: 3000
    networks:
      - sail
    depends_on:
      - laravel.test

  # MySQL
  mysql:
    image: mysql:8.0
    ports:
      - "${FORWARD_DB_PORT:-3306}:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "${DB_PASSWORD:-secret}"
      MYSQL_DATABASE: "${DB_DATABASE:-laravel}"
      MYSQL_USER: "${DB_USERNAME:-sail}"
      MYSQL_PASSWORD: "${DB_PASSWORD:-secret}"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
      - sail-mysql:/var/lib/mysql
      - ./backend/vendor/laravel/sail/database/mysql/create-testing-database.sh:/docker-entrypoint-initdb.d/10-create-testing-database.sh
    networks:
      - sail
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -p${DB_PASSWORD:-secret}"]
      interval: 5s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  # Redis
  redis:
    image: redis:alpine
    ports:
      - "${FORWARD_REDIS_PORT:-6379}:6379"
    volumes:
      - sail-redis:/data
    networks:
      - sail
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  # Mailpit
  mailpit:
    image: axllent/mailpit:latest
    ports:
      - "${FORWARD_MAILPIT_PORT:-1025}:1025"
      - "${FORWARD_MAILPIT_DASHBOARD_PORT:-8025}:8025"
    networks:
      - sail

networks:
  sail:
    driver: bridge

volumes:
  sail-mysql:
    driver: local
  sail-redis:
    driver: local
